bot:
    # Bot token. Changing this requires a bot restart, it will not update when reloading.
    token: "<add-token-here>"

    # Channel where ticket logs are posted (recommended).
    log-channel: 000000000000000000

    # Message posted when a ticket is opened.
    welcome-message: "Please describe your issue below, and include all information needed for us to take action. This is an example ticket message and can be changed in the config."

    # Decides what messages are shown in console. Does not affect the log file.
    # Possible values are: Critical, Error, Warning, Information, Debug.
    console-log-level: "Information"

    # One of the following: LongDate, LongDateTime, LongTime, RelativeTime, ShortDate, ShortDateTime, ShortTime.
    # More info: https://dsharpplus.github.io/api/DSharpPlus.TimestampFormat.html
    timestamp-format: "RelativeTime"

    # Whether staff members should be randomly assigned tickets when they are made. Individual staff members can opt out using the toggleactive command.
    random-assignment: true

    # If set to true the rassign command will include staff members set as inactive if a specific role is specified in the command.
    # This can be useful if you have admins set as inactive to not automatically receive tickets and then have moderators elevate tickets when needed.
    random-assign-role-override: true

    # Sets the type of activity for the bot to display in its presence status.
    # Possible values are: Playing, Streaming, ListeningTo, Watching, Competing, Custom.
    presence-type: "ListeningTo"

    # Sets the activity text shown in the bot's status
    presence-text: "/new"

    # Set to true if you want the /new command to show a selection box instead of a series of buttons.
    new-command-uses-selector: false

    ticket-limits:
        # Maximum number of tickets a single user can have open at a time, staff members are excluded from this.
        # Set to 0 to disable limit.
        user: 5
        # Maximum number of tickets that can be open at a time.
        # Set to 0 to disable limit.
        total: 0

    # Pins the first message in a ticket to allow for quick navigation to the top in large tickets.
    pin-first-message: true

    # Ticket transcript location, can be overridden using command line arguments.
    # When running the bot as a service this will be set to "/var/lib/supportboi/transcripts" by the service.
    transcript-dir: "./transcripts"

    # Log all console output to a file, can be overridden using command line arguments. Set to "" to disable.
    # When running the bot as a service this will be set to "/var/log/supportboi/supportboi.log" by the service.
    # The log file will still log all log levels regardless of the console log level setting.
    log-file: ""

    # Adds the number of tickets open in a category to the end of the category name.
    add-category-ticket-count: true

# Direct message notifications
notifications:
    # Notifies the assigned staff member when a new message is posted in a ticket if the ticket has been silent for a configurable amount of time.
    # Other staff members and bots do not trigger this.
    ticket-updated: true

    # The above notification will only be sent if the ticket has been silent for more than this amount of days. Default is 0.5 days.
    ticket-updated-delay: 0.5

    # Notifies staff when they are assigned to tickets.
    assignment: true

    # Notifies the user opening the ticket that their ticket was closed and includes the transcript.
    closing: true

interviews:
    # Enable the interview system. You must set up interview templates before you can start using it.
    # Any existing interviews can still be completed while interviews are disabled, but new ones will not be created.
    enabled: true

    # Whether to delete the interview question and answer messages after an interview ends.
    delete-messages-after-interview-end: true

database:
    # Address and port of the mysql server.
    address: "127.0.0.1"
    port: 3306

    # Name of the database to use.
    name: "supportboi"

    # Username and password for authentication.
    user: "supportboi"
    password: ""
